name: Test Project

on:
  pull_request:
    branches:
      - main
        

  jobs:
    test:
      runs-on: ubuntu-latest
      setup:
        - uses: actions/checkout@3
        - run: npm ci
        - run: npm test
        - run: npm run build